### ISSUE TITLE
create figma desgin for ENTER

### ISSUE THREAD

**Issue by garengh4** [garengh4/workflix-frontend#86]
what is workflix? 

reference anju's spec + meeting notes: "some sort of internal file management project"?

Dear All

Thanks for joining the call today . Below are the high level project requirements 

Create a WebApp for a B2C situation –

Where an individual can create child / family users ( like Netflix) etc which can be independently access but linked 
Allow each user to upload – Videos/ Doc/ pdf or comments /blogs etc 
Data is stored in a Cloud database
Each of the files can be shared over whatsapp , Mails etc 

For the above create a UI / UX design on a selected tool like figma and then work on detailed architecture defining Database , Microservices and Webservice to be hosted on AWS / Azure 

At a later point in time we will run AI  on the selected files (uploaded)

Regards
Anju

**Comment by LalitSehgal28** [comment]
Add a button with arrow to move to login page when clicked, add a small description to show what we are about, in bottom add github symbol and link to github, see sample apps to see what to do
